### ISSUE TITLE
Model Naming

### ISSUE THREAD

**Issue by BenSto** [00Bock/RubyCars#26]
Ich glaube wir haben schonmal kurz drüber gesprochen... Ich wäre dafür, analog zu pybikes, die Modelle CarShareSystem (momentan Provider) und CarShareStation (momentan Station) zu nennen. Dann würde ich unsere Scraper Klasse auch gerne umbenennen. Ich wäre dafür Sie, um unsere bzw. die von Joscha zum Großteil bisher entwickelte Software ( :+1: ) im Namen zu haben, RubyCars zu nennen o.ä. 

Das hier ist natürlich nur meine Meinung, bin gerne für Diskussionen zu haben.

**Comment by 00Bock** [comment]
:+2:

**Comment by BenSto** [comment]
Außerdem sollten wir in dem Zuge auch vielleicht festzurren, welche Pflichtfelder die Stations Infos haben sollen. Ich denke, diese Pflichtfelder würde Sinn machen, dazu noch ein Bereich extra (JSON), wo Provider spezifische Informationen noch mit eingebracht werden könnten (zum Beispiel Autokennzeichen, Autotypen o.ä.)

        self.name = name
        self.latitude = latitude
        self.longitude = longitude
        self.cars = cars
        self.free = free
        self.id = id
        self.timestamp = Time.now.utc
        self.extra = extra or {}

Beispiel:

      {
        "name": "P\u0119tla Autobusowa - Dambonia", 
        "latitude": 50.6617752662236, 
        "longitude": 17.8888911008835, 
        "free_cars": 0, 
        "empty_slots": 10, 
        "id": "d8c9f66260759aeb27445b2cddf2d6b9", 
        "timestamp": "2016-01-12T08:17:36.455Z",
        "extra": {
          "slots": "10", 
          "uid": 132115
        }, 
      },

**Comment by kjoscha** [comment]
okay, hier angefangen https://github.com/00Bock/RubyCars/commit/8312794ed34519eecf29404ea1fe6f2160cfe6bc

gerne mal drüber schauen
