### ISSUE TITLE
Workflow and repository structure for collaboration

### ISSUE THREAD

**Issue by 00Bock** [00Bock/RubyCars#37]
Womit wollen wir rausgehen. Ist es dieses Repository oder wollen wir ein öffentliches repo nur mit scraping scripten?

**Comment by kjoscha** [comment]
Ich fände es cool und einfach, wenn wir hiermit rausgehen. Soweit ich weiß, können andere User eh nur PR's stellen.
http://stackoverflow.com/questions/17442930/can-anybody-push-to-my-project-on-github

**Comment by kjoscha** [comment]
ist für die Contributers auch einfacher zu entwickeln dann, weil sie ihre Scraping-Skripte direkt an ihrer lokalen Kopie der Webseite testen können...

**Comment by BenSto** [comment]
>  No, but if the repository is public others can fork it, commit to their own fork.
They can then ask you to pull some of the changes in their fork into your repository via a pull-request.

Ich denke genau der Teil aus dem Link von @kjoscha  sollte dann der normale Workflow für Leute sein, die sich beteiligen wollen.

**Comment by kjoscha** [comment]
zumal es ja auch cool ist, wenn externe Leute die Webseite verbessern

**Comment by 00Bock** [comment]
wird natürlich schwieriger, bei uns intern zu vertreten. da wird vielleicht die verantwortlichkeit der webseite nicht mehr bei der innoz liegen...

**Comment by kjoscha** [comment]
>wird natürlich schwieriger, bei uns intern zu vertreten. da wird vielleicht die verantwortlichkeit der webseite nicht mehr bei der innoz liegen...

dafür bräuchte man wohl mal eine generelle Diskussion darüber, wie das INNOVATIONSZENTRUM InnoZ dem Thema OpenSource und der Partizipation daran gegenübersteht!

**Comment by 00Bock** [comment]
Ja, hier geht es natürlich auch um Dritte neben dem InnoZ und den Entwicklern. Wir werden uns hierzu mal vorsichtig herantasten. Problematisch ist es schon hier ein öffentliches Repo für z.B. solche diskussionen zu führen und steht ggf. im Wiederspruch zu Geheimhaltungsvereinbarungen, die wir alle mal unterschrieben haben. Wir müssen trotz der Bestreben nach OpenSource ganz klar eine Grenze ziehen, z.B. einen Codex worüber wir im Repo diskutieren und worüber nicht. Da wir hier schon ein paar Sachen besprechen, die eher intern gedacht sind, müssen wir in irgendeiner Form handeln.

**Comment by BenSto** [comment]
100% Signed.
