### ISSUE TITLE
Rubocop etc.

### ISSUE THREAD

**Issue by BenSto** [00Bock/RubyCars#44]
Ich will ja nicht nerven, aber ich habe neulich erst alle offenses gefixt. Die sind sämtlich wieder im Master gelandet. Entweder wir nutzen Rubocop oder wir schaffen es gleich ab.

53 files inspected, 48 offenses detected......

**Comment by BenSto** [comment]
Hmm dazu habe ich letzte Woche 2 Provider hinzugefügt, die sind auch spurlos verschwunden..

**Comment by 00Bock** [comment]
das wäre ja blöd, wenn die offences wieder auftreten und die provider verschwinden. Wie kann denn das mit git passieren?

**Comment by BenSto** [comment]
ich verstehe es ehrlich gesagt auch nicht ganz.

**Comment by 00Bock** [comment]
vielleicht ein fall für git reset?

**Comment by BenSto** [comment]
hmm anscheinend wurde der recht alte api branch in den master gemerged.. vielleicht ohne vorherigen rebase.. und dann push -f .. anders kann ich es mir nicht erklären. Aber so wie es aussieht, sind die alten Commits weg. Da ich der Ordnung halber die alten Branches nach dem merge gelöscht habe.. was auch so üblich ist, um nicht einen Branch Wald zu erzeugen.

**Comment by BenSto** [comment]
Vielleicht kann @kjoscha nach seiner Rückkehr das Rätsel lösen.

**Comment by BenSto** [comment]
in der commit history sind die branches und commits noch... gut dann ist es nicht ganz so dramatisch
